### ISSUE TITLE
Rename rails generator

### ISSUE THREAD

**Issue by northox** [mantor/floristry#11]
**[Original report](https://bitbucket.org/northox/active-trail/issue/11) by Jean-François Rioux (Bitbucket: [jfrioux](https://bitbucket.org/jfrioux), GitHub: [jfrioux](https://github.com/jfrioux)).**

----------------------------------------

Rename 

* rails g active_trail:install
* rails g active_trail:participant

to

* rails g floristry:install
* rails g floristry:participant

**Comment by jfrioux** [comment]
Closed by 4c666e3
