### ISSUE TITLE
Why can't we see completed Audit trail?

### ISSUE THREAD

**Issue by northox** [mantor/floristry#33]
The dummy app, and users of Floristry, need to see completed/executed Workflow. We should be able to see what's running and want's already completed. (Eventually we could actually see what's coming (things scheduled).

**Comment by jfrioux** [comment]
We do see the terminated Workflows + counters at the bottom correctly updated.
Something else was faulty in our set-up when we noticed that.

**Comment by northox** [comment]
Good news.
