### ISSUE TITLE
find_cnodes() error - BLOCKER

### ISSUE THREAD

**Issue by northox** [mantor/floristry#41]
Starting from a fresh Flor's DB and fresh Trail, a workflow with `sequence \ alice _ \ sleep '5h'` fails. It's looking for a non existant cnodes in `find_cnodes()`.

**Comment by jfrioux** [comment]
Please make sure you follow the new install procedure highlighted in #38, and let me know if you still face the issue. Make sure to flush your `active_trails_` db tables.

I'm testing on my side, with the workflow you posted as an example, and I'm not having the issue. 
I want to se if this is not a false positive.
Thank you,
