### ISSUE TITLE
Install hooks and taskers to a remote flack

### ISSUE THREAD

**Issue by jfrioux** [mantor/floristry#50]
Find a way to provide easy installation of the hooks and taskers found under `lib/generators/floristry/templates/flack/lib` to a remote Flack.

**Comment by northox** [comment]
What about adding this action to flask?

**Comment by jfrioux** [comment]
One part of the issue was fixed by cloning https://github.com/floraison/pollen in the appropriate directory on the flack side.

Pending: the taskers

**Comment by northox** [comment]
Now that taskers are a separate repository, this should be easy to complete.
